export type RiskLevel = "high" | "medium" | "low"
export type PatientStatus = "awaitingDoctor" | "testPending" | "underTreatment" | "cleared"
export type RiskFactorAnswer = "yes" | "no" | "dontKnow" | "preferNotToSay"

export interface Patient {
  id: string
  name: string
  nameHi: string
  age: number
  gender: "male" | "female" | "other"
  phone: string
  address: string
  addressHi: string
  pincode: string
  village?: string
  villageHi?: string
  aadhar?: string
  riskScore: number
  riskLevel: RiskLevel
  status: PatientStatus
  distanceToPHC: number // in km
  needsSync: boolean
  testScheduled: boolean
  
  // Vitals
  weight?: number
  height?: number
  heartRateBpm?: number
  bodyTemperature?: number
  bodyTemperatureUnit?: "C" | "F"
  
  // Clinical Data
  coughDuration?: number
  coughNature?: "dry" | "wet" | "bloodStained"
  feverHistory?: "none" | "lowGrade" | "highGrade"
  nightSweats?: RiskFactorAnswer
  weightLoss?: RiskFactorAnswer
  physicalSigns?: string[]
  riskFactors?: string[]
  riskFactorAnswers?: Record<string, RiskFactorAnswer>
  otherObservations?: string
  
  // AI Analysis
  hearAudioScore?: number
  medGemmaReasoning?: string
  
  // Dates
  createdAt: string
  collectionDate: string
  scheduledTestDate?: string

  // Sample ID for lab matching
  sampleId?: string
  
  // GPS Location (stored but not displayed)
  latitude?: number
  longitude?: number
}

export const mockPatients: Patient[] = [
  {
    id: "P001",
    name: "Ramesh Kumar",
    nameHi: "रमेश कुमार",
    age: 45,
    gender: "male",
    phone: "+91 98765 43210",
    address: "House No. 45, Main Road, Rampur Village",
    addressHi: "मकान नंबर 45, मुख्य सड़क, रामपुर गाँव",
    pincode: "847226",
    village: "Rampur",
    villageHi: "रामपुर",
    riskScore: 9.5,
    riskLevel: "high",
    status: "awaitingDoctor",
    distanceToPHC: 8.5,
    needsSync: false,
    testScheduled: true,
    weight: 58,
    height: 170,
    coughDuration: 42,
    coughNature: "bloodStained",
    feverHistory: "highGrade",
    physicalSigns: ["chestPain", "shortnessOfBreath", "extremeFatigue"],
    riskFactors: ["historyOfTB", "smoker"],
    otherObservations: "Living in crowded slum area. Previous TB treatment incomplete.",
    hearAudioScore: 0.92,
    medGemmaReasoning: "Patient shows classic hemoptysis with prolonged cough. Night sweats and weight loss indicate active TB. Previous incomplete treatment suggests possible drug resistance. URGENT: Immediate isolation and GeneXpert testing required.",
    createdAt: "2026-01-28",
    collectionDate: "2026-01-28",
    scheduledTestDate: "2026-02-06",
    latitude: 26.8467,
    longitude: 80.9462,
  },
  {
    id: "P002",
    name: "Sunita Devi",
    nameHi: "सुनीता देवी",
    age: 32,
    gender: "female",
    phone: "+91 87654 32109",
    address: "Near Temple, Ward 3, Kishanganj Town",
    addressHi: "मंदिर के पास, वार्ड 3, किशनगंज टाउन",
    pincode: "855107",
    village: "Kishanganj",
    villageHi: "किशनगंज",
    riskScore: 9.2,
    riskLevel: "high",
    status: "testPending",
    distanceToPHC: 12.3,
    needsSync: false,
    testScheduled: false,
    weight: 45,
    height: 155,
    coughDuration: 56,
    coughNature: "wet",
    feverHistory: "highGrade",
    physicalSigns: ["shortnessOfBreath", "lossOfAppetite", "extremeFatigue"],
    riskFactors: ["familyMemberHasTB", "diabetes"],
    otherObservations: "Husband currently on TB treatment. Significant weight loss in past month.",
    hearAudioScore: 0.88,
    medGemmaReasoning: "High suspicion of pulmonary TB with household contact. Prolonged productive cough with constitutional symptoms. Diabetes increases TB risk. Priority testing recommended.",
    createdAt: "2026-01-25",
    collectionDate: "2026-01-25",
    latitude: 26.1009,
    longitude: 87.9500,
  },
  {
    id: "P003",
    name: "Mohan Lal",
    nameHi: "मोहन लाल",
    age: 55,
    gender: "male",
    phone: "+91 76543 21098",
    address: "Plot 12, Sector B, Darbhanga City",
    addressHi: "प्लॉट 12, सेक्टर बी, दरभंगा शहर",
    pincode: "846004",
    village: "Darbhanga",
    villageHi: "दरभंगा",
    riskScore: 6.8,
    riskLevel: "medium",
    status: "awaitingDoctor",
    distanceToPHC: 5.2,
    needsSync: false,
    testScheduled: true,
    weight: 62,
    height: 168,
    coughDuration: 28,
    coughNature: "wet",
    feverHistory: "lowGrade",
    physicalSigns: ["chestPain", "lossOfAppetite"],
    riskFactors: ["smoker"],
    hearAudioScore: 0.65,
    medGemmaReasoning: "Moderate TB suspicion. Productive cough with low-grade fever. Smoking history increases respiratory risk. Sputum examination advised.",
    createdAt: "2026-01-30",
    collectionDate: "2026-01-30",
    scheduledTestDate: "2026-02-09",
    latitude: 26.1542,
    longitude: 85.8918,
  },
  {
    id: "P004",
    name: "Lakshmi Prasad",
    nameHi: "लक्ष्मी प्रसाद",
    age: 28,
    gender: "female",
    phone: "+91 65432 10987",
    address: "Gali No. 7, Bazaar Road, Sitamarhi",
    addressHi: "गली नंबर 7, बाज़ार रोड, सीतामढ़ी",
    pincode: "843302",
    village: "Sitamarhi",
    villageHi: "सीतामढ़ी",
    riskScore: 5.5,
    riskLevel: "medium",
    status: "testPending",
    distanceToPHC: 15.8,
    needsSync: false,
    testScheduled: false,
    weight: 52,
    height: 160,
    coughDuration: 21,
    coughNature: "dry",
    feverHistory: "lowGrade",
    physicalSigns: ["extremeFatigue"],
    riskFactors: [],
    hearAudioScore: 0.52,
    medGemmaReasoning: "Low-moderate TB suspicion. Dry cough with mild fever. No significant risk factors. Monitor and retest if symptoms persist beyond 2 weeks.",
    createdAt: "2026-02-01",
    collectionDate: "2026-02-01",
    latitude: 26.5952,
    longitude: 85.4810,
  },
  {
    id: "P005",
    name: "Rajesh Singh",
    nameHi: "राजेश सिंह",
    age: 40,
    gender: "male",
    phone: "+91 54321 09876",
    address: "Village Madhubani, Near School, Post Office Road",
    addressHi: "गाँव मधुबनी, स्कूल के पास, डाकघर रोड",
    pincode: "847211",
    village: "Madhubani",
    villageHi: "मधुबनी",
    riskScore: 7.2,
    riskLevel: "medium",
    status: "underTreatment",
    distanceToPHC: 7.0,
    needsSync: false,
    testScheduled: false,
    weight: 55,
    height: 172,
    coughDuration: 35,
    coughNature: "wet",
    feverHistory: "highGrade",
    physicalSigns: ["shortnessOfBreath", "lossOfAppetite"],
    riskFactors: ["historyOfTB"],
    hearAudioScore: 0.71,
    medGemmaReasoning: "Patient on DOTS therapy. Previous TB history. Current symptoms may indicate treatment response needs evaluation. Continue treatment with close monitoring.",
    createdAt: "2026-01-15",
    collectionDate: "2026-01-15",
    latitude: 26.3508,
    longitude: 86.0712,
  },
  {
    id: "P006",
    name: "Geeta Kumari",
    nameHi: "गीता कुमारी",
    age: 22,
    gender: "female",
    phone: "+91 43210 98765",
    address: "House 23, Mohalla Sadar, Samastipur",
    addressHi: "मकान 23, मोहल्ला सदर, समस्तीपुर",
    pincode: "848101",
    village: "Samastipur",
    villageHi: "समस्तीपुर",
    riskScore: 3.2,
    riskLevel: "low",
    status: "cleared",
    distanceToPHC: 4.5,
    needsSync: false,
    testScheduled: false,
    weight: 48,
    height: 158,
    coughDuration: 7,
    coughNature: "dry",
    feverHistory: "none",
    physicalSigns: [],
    riskFactors: [],
    hearAudioScore: 0.25,
    medGemmaReasoning: "Low TB suspicion. Short duration dry cough likely viral. No risk factors. Symptomatic treatment advised. Follow up if symptoms worsen.",
    createdAt: "2026-01-20",
    collectionDate: "2026-01-20",
    latitude: 25.8628,
    longitude: 85.7784,
  },
  {
    id: "P007",
    name: "Vijay Yadav",
    nameHi: "विजय यादव",
    age: 60,
    gender: "male",
    phone: "+91 32109 87654",
    address: "Station Road, Ward 5, Muzaffarpur City",
    addressHi: "स्टेशन रोड, वार्ड 5, मुजफ्फरपुर शहर",
    pincode: "842001",
    village: "Muzaffarpur",
    villageHi: "मुजफ्फरपुर",
    riskScore: 4.5,
    riskLevel: "low",
    status: "testPending",
    distanceToPHC: 10.2,
    needsSync: false,
    testScheduled: true,
    weight: 70,
    height: 175,
    coughDuration: 14,
    coughNature: "dry",
    feverHistory: "lowGrade",
    physicalSigns: ["chestPain"],
    riskFactors: ["diabetes"],
    hearAudioScore: 0.38,
    medGemmaReasoning: "Low-moderate suspicion. Age and diabetes are risk factors. Short duration cough needs monitoring. Routine sputum test scheduled.",
    createdAt: "2026-02-02",
    collectionDate: "2026-02-02",
    scheduledTestDate: "2026-02-09",
    latitude: 26.1197,
    longitude: 85.3910,
  },
  {
    id: "P008",
    name: "Priya Sharma",
    nameHi: "प्रिया शर्मा",
    age: 35,
    gender: "female",
    phone: "+91 21098 76543",
    address: "Apartment 4B, Gandhi Nagar, Begusarai",
    addressHi: "अपार्टमेंट 4बी, गांधी नगर, बेगूसराय",
    pincode: "851101",
    village: "Begusarai",
    villageHi: "बेगूसराय",
    riskScore: 2.8,
    riskLevel: "low",
    status: "cleared",
    distanceToPHC: 6.8,
    needsSync: false,
    testScheduled: false,
    weight: 55,
    height: 162,
    coughDuration: 7,
    coughNature: "dry",
    feverHistory: "none",
    physicalSigns: [],
    riskFactors: [],
    hearAudioScore: 0.18,
    medGemmaReasoning: "Very low TB suspicion. Symptoms consistent with seasonal allergies. No further TB workup needed at this time.",
    createdAt: "2026-01-18",
    collectionDate: "2026-01-18",
    latitude: 25.4182,
    longitude: 86.1272,
  },
  {
    id: "P009",
    name: "Arjun Thakur",
    nameHi: "अर्जुन ठाकुर",
    age: 48,
    gender: "male",
    phone: "+91 10987 65432",
    address: "Tilak Nagar, Block C, Bhagalpur",
    addressHi: "तिलक नगर, ब्लॉक सी, भागलपुर",
    pincode: "812001",
    village: "Bhagalpur",
    villageHi: "भागलपुर",
    riskScore: 5.8,
    riskLevel: "medium",
    status: "awaitingDoctor",
    distanceToPHC: 18.5,
    needsSync: false,
    testScheduled: false,
    weight: 60,
    height: 170,
    coughDuration: 28,
    coughNature: "wet",
    feverHistory: "lowGrade",
    physicalSigns: ["lossOfAppetite", "extremeFatigue"],
    riskFactors: ["smoker"],
    hearAudioScore: 0.58,
    medGemmaReasoning: "Moderate suspicion. Chronic smoker with productive cough. Constitutional symptoms present. Sputum AFB and chest X-ray recommended.",
    createdAt: "2026-02-03",
    collectionDate: "2026-02-03",
    latitude: 25.2425,
    longitude: 86.9842,
  },
  {
    id: "P010",
    name: "Meera Gupta",
    nameHi: "मीरा गुप्ता",
    age: 50,
    gender: "female",
    phone: "+91 09876 54321",
    address: "Boring Road, Near Hospital, Patna",
    addressHi: "बोरिंग रोड, अस्पताल के पास, पटना",
    pincode: "800001",
    village: "Patna",
    villageHi: "पटना",
    riskScore: 3.5,
    riskLevel: "low",
    status: "underTreatment",
    distanceToPHC: 2.0,
    needsSync: false,
    testScheduled: false,
    weight: 58,
    height: 155,
    coughDuration: 14,
    coughNature: "dry",
    feverHistory: "none",
    physicalSigns: ["chestPain"],
    riskFactors: ["diabetes"],
    hearAudioScore: 0.32,
    medGemmaReasoning: "Low suspicion but on preventive therapy due to diabetes and age. Completing IPT course. Regular monitoring continues.",
    createdAt: "2026-01-10",
    collectionDate: "2026-01-10",
    latitude: 25.6093,
    longitude: 85.1376,
  },
]

// Statistics calculated from mock data
export function getStats(patients: Patient[]) {
  const today = new Date().toISOString().split("T")[0]
  return {
    highRisk: patients.filter((p) => p.riskLevel === "high").length,
    pendingUploads: patients.filter((p) => p.needsSync).length,
    testsToday: patients.filter((p) => p.scheduledTestDate === today || (p.testScheduled && p.scheduledTestDate === today)).length,
    total: patients.length,
  }
}
